POST http://localhost:5000/add/internshipcourse HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWFscGl6YXJwIiwiaWF0IjoxNjUyMzIxMDExfQ.X6nAQ6KkCc7xOpS3QPHWOALj4swn7_F6JDNLEQhANlo
content-type: application/json

{
    "courseId": "IC-4810",
    "internshipId": "I-01",
    "hours": 8,
    "date": "November 20",
    "assistant": "Eric Alpizar",
    "groups": 4,
    "type": "Research"
}