POST http://localhost:5000/add/course HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWFscGl6YXJwIiwiaWF0IjoxNjUyMzIxMDExfQ.X6nAQ6KkCc7xOpS3QPHWOALj4swn7_F6JDNLEQhANlo
content-type: application/json

{
    "courseId": "IC-4810",
    "subject": "Investigacion de Operaciones",
    "year": 2022,
    "career": "Ingenieria en Computacion",
    "weeklyHours": 12,
    "professorId": "20106781"
}


