PUT http://localhost:5000/update/course/IC-4810 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZWFscGl6YXJwIiwiaWF0IjoxNjUyMzIxMDExfQ.X6nAQ6KkCc7xOpS3QPHWOALj4swn7_F6JDNLEQhANlo
content-type: application/json
Connection: keep-alive

{
    "subject": "Investigacion de Operaciones",
    "year": 2023,
    "career": "Ingenieria en Computacion",
    "weeklyHours": 13
}